CREATE TABLE BRAND(
ID INT PRIMARY KEY,
NAME VARCHAR(255)
);

CREATE TABLE CAR(
ID INT PRIMARY KEY,
NAME VARCHAR(255),
COLOUR VARCHAR(255),
ID_BRAND INT NOT NULL,
FOREIGN KEY (ID_BRAND) REFERENCES BRAND(ID)
);

CREATE TABLE PRICE(
ID INT PRIMARY KEY,
START_DATE DATE,
END_DATE DATE,
VALUE DOUBLE,
ID_CAR INT NOT NULL,
FOREIGN KEY (ID_CAR) REFERENCES CAR(ID)
);